language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tsungtingdu/docker-visitors -f Dockerfile.dev .

script:
  - docker run -e CI=true tsungtingdu/docker-visitors npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"  
  app: "docker-visitors" 
  env: "DockerVisitors-env"
  bucket_name: "elasticbeanstalk-us-east-2-516245968608"
  bucket_path: "docker-visitors"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY