language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tsungtingdu/docker-visitors -f Dockerfile.dev .

script:
  - docker run -e CI=true tsungtingdu/docker-visitors npm run test -- --coverage